---
title: "modeling2"
format: html
editor: source
---
```{r}
# To start: fit one species. Later: species*log() and interactions for species-specific effects? Hierarchical gams...
# Correlation plots bt env vars - use trawl id key
# Either drop some correlated vars (eg phyto, npp) or use PCA
# Scale env vars - same 0 -1
```

```{r}
library(sdmTMB)
library(ggplot2)
library(surveyjoin)
library(rnaturalearth)
library(stringr)
```

```{r}
# Biological data
fish_all <- readRDS("fish_all.rds")
arrow <- fish_all |> filter(common_name == "arrowtooth flounder")

# Clean missing data and 0s
arrow <- arrow |>
  filter(!is.na(lon), !is.na(weight_kg)) |>
  filter(weight_kg > 0, length_cm > 0) |>
  mutate(year = year(time)) |>
  filter(year >= 2003 & year <= 2023)
```

```{r}
# Time series
m1 <- lm(log(weight_kg) ~ log(length_cm) + factor(year), data = arrow)

df <- tidy(m1)
d <- df |>
  filter(str_detect(term, "year")) |>
  mutate(year = str_remove(term, "^factor\\(year\\)")) |>
  ggplot(aes(x = year, y = exp(estimate))) +
  geom_point() + 
  theme_minimal() +
  labs(x = "Year", y = "exp(estimate)") +
  theme(axis.text.x = element_text(angle = 40, vjust = 0.8, hjust = 1))
#ggsave("example.jpg", d, width = 6, height = 4)

# m2 <- gam(log(Weight) ~ log(Length_cm) + s(Year) + factor(Sex) + factor(Common_name), data = arrowtooth)
# summary(m2)
# 
# m3 <- gam(log(Weight) ~ log(Length_cm) + s(temp, k=4) + s(salinity,k=4) + s(o2,k=4) + s(npp,k=4) + s(phyto,k=4) + factor(Sex), data = arrowtooth)
# summary(m3)
# 
# gam.check(m3)
```


```{r}
# Get grids from surveyjoin and combine
grid_nwfsc <- surveyjoin::nwfsc_grid
grid_pbs <- surveyjoin::dfo_synoptic_grid
grid_afsc <- surveyjoin::afsc_grid

grid <- bind_rows(grid_nwfsc, grid_pbs, grid_afsc)
grid <- add_utm_columns(grid, ll_names = c("lon", "lat"), utm_crs = 32602)
grid <- expand_grid(grid, year = unique(arrow$year))
grid <- grid |>
  mutate(length_cm = mean(arrow$length_cm, na.rm = TRUE))
```

```{r}
# Run model
arrow <- sdmTMB::add_utm_columns(arrow, ll_names = c("lon", "lat"), utm_crs = 32610)
mesh <- sdmTMB::make_mesh(arrow, xy_cols = c("X","Y"), cutoff = 100)
#mesh$mesh$n

mod <- sdmTMB(log(weight_kg) ~ log(length_cm) + factor(year),
         mesh = mesh,
         spatiotemporal = "iid",
         time = "year",
         data = arrow)

# Generate predictions
pred <- predict(mod, grid)
pred <- pred |> mutate(est2 = exp(est))
```

```{r}
# Get base maps
states <- ne_download(scale = 50, type = "states", category = "cultural", returnclass = "sf")
states <- states |> filter(admin == "United States of America")
canada <- ne_download(scale = 50, type = "states", category = "cultural", returnclass = "sf")
canada <- canada |> filter(admin == "Canada") |> select(name, geometry)
mexico <- ne_countries(scale = "medium", returnclass = "sf", country = "mexico") |> 
  select(name = admin, geometry)
alaska <- states |> filter(.data$name == "Alaska")

combined <- bind_rows(states, canada, mexico, alaska)
proj <- st_transform(combined, crs = 3157)
proj <- suppressWarnings(st_crop(proj, c(xmin = -5500000, ymin = 3350000, xmax = 1200000, ymax = 8000000)))
#proj <- suppressWarnings(st_crop(proj, c(xmin = -126, ymin = 30, xmax = -117, ymax = 50)))
proj <- st_transform(proj, 4326)
rm(states, canada, mexico, alaska, combined)
```

```{r}
pred_sf <- pred |>
  st_as_sf(coords = c("lon", "lat"), crs = 4326) |>
  st_transform(3338)
pred <- pred |>
  mutate(x = st_coordinates(pred_sf)[,1], y = st_coordinates(pred_sf)[,2])
rm(pred_sf)

ggplot() +
      stat_summary_hex(data = pred, aes(x = x, y = y, z = est2), bins = 50) +
      scale_fill_viridis_c(name = "weight (kg)") +
      geom_sf(data = proj) +
      coord_sf(crs = 3338, expand = FALSE) +  # Alaska Albers Equal Area
      geom_sf_text(data = proj, aes(label = name), size = 2, fontface = "bold", check_overlap = F) +
      theme_minimal() 
```

```{r}
library(gganimate)

p <- ggplot() +
      stat_summary_hex(data = pred, aes(x = x, y = y, z = est2), bins = 50) +
      scale_fill_viridis_c(name = "weight (kg)") +
      geom_sf(data = proj) +
      coord_sf(crs = 3338, expand = FALSE) +  # Alaska Albers Equal Area
      geom_sf_text(data = proj, aes(label = name), size = 2.5, fontface = "bold", check_overlap = F) +
      theme_minimal() +
  labs(title = "Year: {closest_state}") +
  transition_states(year, transition_length = 1, state_length = 1)

animate(p, fps = 5, width = 700, height = 700)
```

